version: '3'

services:
  db:
    image: mariadb:10.7.1-focal
    container_name: db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
      - MYSQL_ROOT_PASSWORD=wordpress
    volumes: 
      - ./mariadb/data:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:6.2.6-alpine
    container_name: redis
    restart: unless-stopped
    volumes: 
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/logs:/logs
    networks:
      - app-network

  wordpress:
    depends_on: 
      - db
    image: wordpress:5.8-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network
  
  webserver:
    depends_on:
      - wordpress
    image: nginx:1.21.4-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    networks:
      - app-network

  certbot:
    depends_on:
      - webserver
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
      - ./certbot/logs/:/var/log/letsencrypt/:rw
    command: certonly --webroot --webroot-path=/var/www/certbot --email guisheng.xiong@gmail.com --agree-tos --no-eff-email --staging -d xiongguisheng.com -d www.xiongguisheng.com
    networks:
      - app-network

volumes:
  wordpress:

networks:
  app-network:
    driver: bridge  
